# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('director', models.CharField(max_length=128)),
                ('imdb_score', models.DecimalField(decimal_places=2, max_digits=20)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
